### ISSUE TITLE
[RFC] stock_inventory_abc

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-warehouse#1364]
This module allows you to implement ABC Analysis and configure cycle count rules using the ABC group.
The type "ABC Analysis" on cycle count rule will schedule a cycle count based on the frequency (daily, weekly, monthly or quarterly) and make sure:

* A products are counted 4 times a year
* B products are counted twice a year
* C products are counted once a year

# Configuration

* Set your products in one of the ABC group
* Create your cycle count rules using the ABC Analysis and set the frequency
* Go to the warehouses to compute the rules
* Review the cycle count

# Usage

* Based on the frequency, review the cycle counts and confirm the relevant ones
* Perform the counting based on the location and products of the inventory adjustments
* Update and validate the inventory adjustment

# Roadmap

Known limitations:

* Since the user can change the group of a product during the year, the number of actual counts in a year may not match the one of the group. --> Use Odoo data to compute the group annually based on the ABC Analysis and make the "ABC Group" field on the product read-only.

# Dependencies

stock_cycle_count

# License

AGPL-3

# Technical Specifications

## stock.abc

- [ ] Add a required char field "Name" (name)
- [ ] Add a required integer field "Count per year" (count)
- [ ] Add data with

Name | Count per year
-- | --
A | 4
B | 2
C | 1

## product.template

- [ ] Add a many2one field "ABC Group" (abc_id) to stock.abc
- [ ] Add a new group "Cycle Count" with the "ABC Group" field
- [ ] Hide the group if the product type is not "product"
  * Make the "ABC Group" field required if the product type is "product"
  * Add the "ABC Group" field in the dynamic columns list just after Product Type; by default keep this one hidden

## stock.cycle.count.rule

- [ ] Add an option "ABC Analysis" (abc) in the type of rule selection field
- [ ] Add a selection field "Frequency" (frequency) with "Daily", "Weekly", "Monthly" and "Quarterly"
- [ ] When rules are computed
  * if type is abc, generate a cycle count for each warehouse/location (not sublocations) based on the frequency

## stock.cycle.count

- [ ] When the count is confirmed, if the type of the rule is abc
  * Create one inventory adjustment "Name of the location - Date"
  * Take all the products of the group
  * Remove the ones that are in an inventory adjustment (linked to the same cycle count rule) in the last X
    * If frequency = daily --> X = 365 / count per year of the group; days prior to the date in that warehouse/location
    * If frequency = weekly --> X = 52 / count per year of the group; weeks prior to the date in that warehouse/location
    * If frequency = monthly --> X = 12 / count per year of the group; months prior to the date in that warehouse/location
    * If frequency = quarterly --> X = 12 / count per year of the group; months prior to the date in that warehouse/location
  * Keep the first Y of the remaining products (round to the greater integer)
    * If frequency = daily --> Y = Total number of product in the group * count per year of the group / 365
    * If frequency = weekly --> Y = Total number of product in the group * count per year of the group / 52
    * If frequency = monthly --> Y = Total number of product in the group * count per year of the group / 12
    * If frequency = quarterly --> Y = Total number of product in the group * count per year of the group / 4
  * Create a inventory adjustment line for each product and sublocation of the warehouse / location if the quantity on hand for that product in that location is not zero
