### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-warehouse#201]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] base_product_merge
- [ ] business_product_location - By @rousseldenis - #446 
- [ ] configurable_stock_level
- [ ] partner_location_auto_create
- [x] stock_available - By @SodexisTeam - #219
- [x] stock_available_immediately - By @SodexisTeam - #219
- [x] stock_available_mrp - @Cedric-Pigeon #280
- [x] stock_available_sale - By @chienandalu - #334 
- [x] stock_available_unreserved - By @StefanRijnhart - #283
- [ ] stock_inventory_line_price - @dlasley #276
- [ ] stock_inventory_preparation_filter
- [ ] stock_location_area_data
- [ ] stock_location_area_management
- [ ] stock_location_lockdown - By @alexis-via  - #516 
- [ ] stock_location_ownership
- [ ] stock_lot_valuation
- [ ] stock_move_location
- [x] stock_mts_mto_rule - By @sylvain-garancher - #203 
- [ ] stock_optional_valuation
- [ ] stock_orderpoint_creator
- [ ] stock_partner_lot
- [x] stock_product_location_sorted_by_qty - By @chafique-delli - #444 
- [x] stock_putaway_product - By @rousseldenis - #255
- [x] stock_quant_manual_assign - By @fanha99 - #326
- [x] stock_quant_merge - By @lreficent - #265 
- [ ] stock_reord_rule
- [ ] stock_reserve - By @andrius-preimantas - #239 
- [ ] stock_reserve_sale

**Comment by Garamotte** [comment]
Migration of stock_mts_mto_rule here : https://github.com/OCA/stock-logistics-warehouse/pull/203
(Including #157 which migrates from v8.0 to v9.0, but is not yet merged)

**Comment by SodexisTeam** [comment]
We are planning to migrate stock_available and stock_available_immediately.

**Comment by pedrobaeza** [comment]
OK, written in the main comment

**Comment by atchuthan** [comment]
Created PR https://github.com/OCA/stock-logistics-warehouse/pull/219 for stock_available & stock_available_immediately.

**Comment by kkarolis** [comment]
Planning to migrate stock_reserve & stock_reserve_sale (blocking #190)

Edit:
Added a longstanding PR

**Comment by mrparadies** [comment]
Are there any plans to upgrade the stock_available_mrp module?

**Comment by SodexisTeam** [comment]
@mrparadies we migrated for a client and haven't completed the demo/tests related to it in PR:https://github.com/OCA/stock-logistics-warehouse/pull/248.

**Comment by LoisRForgeFlow** [comment]
Migrated and needing review:
https://github.com/OCA/stock-logistics-warehouse/pull/261 stock_orderpoint_uom
https://github.com/OCA/stock-logistics-warehouse/pull/262 account_move_line_product
https://github.com/OCA/stock-logistics-warehouse/pull/263 stock_quant_reserved_qty_uom
https://github.com/OCA/stock-logistics-warehouse/pull/264 account_move_line_stock_info
https://github.com/OCA/stock-logistics-warehouse/pull/265 stock_quant_merge

**Comment by safecoms** [comment]
Are there any plans to upgrade to v10 the stock_cycle_count module?

**Comment by BetaUliansyah** [comment]
I am waiting for version 10 upgarde of stock_reserve and stock_reserve_sale. What can I do to make it available soon?

**Comment by pedrobaeza** [comment]
stock_reserve is migrated in https://github.com/OCA/stock-logistics-warehouse/pull/239. Review it.

**Comment by BetaUliansyah** [comment]
Currently, in my version 10 odoo, I am using stock_reserve #239 and stock_reserve_sale #190 (its v9, but installable to v10).

**Comment by pedrobaeza** [comment]
OK, then you can add a comment on #239 saying that it's working so it helps to speed up the review process
