### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-warehouse#343]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] account_move_line_product - ~~By @VRodrigo - #354~~ By @mreficent - #471 
- [x] account_move_line_stock_info - By @mreficent - #472 
- [x] packaging_uom - By @jhumfer - #469 
- [ ] partner_location_auto_create - By @BT-kaberer - #443 
- [x] procurement_auto_create_group - By @lreficent - #482 
- [ ] sale_packaging - By @rousseldenis - #492 
- [x] stock_available - ~~By @kikopeiro - #353~~ - By @asaunier - #405 
- [x] stock_available_immediately - By @dmsergio - #778 
- [x] stock_available_mrp - By @tschanzt - #428 
- [ ] stock_available_sale
- [x] stock_available_unreserved - By @mpanarin - #375 
- [x] stock_change_qty_reason - By @andreasdsp - #417 
- [x] stock_cycle_count - By @lreficent - #484 
- [x] stock_demand_estimate - By @mpanarin - #381
- [x] stock_inventory_chatter - ~~By @reynaldiyosfino - #424~~ - By @xavierjimenez - #451 
- [x] stock_inventory_discrepancy - By @andreasdsp - #418 
- [x] stock_inventory_exclude_sublocation - By @lreficent - #478
- [x] stock_inventory_lockdown - By @lreficent - #479 
- [x] stock_inventory_preparation_filter - By @xavierjimenez - #452 
- [x] stock_inventory_verification_request - By @lreficent - #480
- [ ] stock_location_area_data
- [ ] stock_location_area_management
- [ ] stock_location_ownership
- [ ] stock_lot_valuation
- [x] stock_move_location - ~~By @mpanarin - #522~~ By @sebalix - #535 
- [x] stock_mts_mto_rule - By @florian-dacosta - #399 
- [ ] stock_operation_package_mandatory
- [ ] stock_optional_valuation
- [ ] stock_orderpoint_automatic_creation - ~~By @andreasdsp - #429~~ By @ValentinVinagre - #502 
- [ ] stock_orderpoint_creator
- [x] stock_orderpoint_generator - By @cubells #488 
- [x] stock_orderpoint_manual_procurement - By @bodedra - #385 
- [x] stock_orderpoint_manual_procurement_uom - By @bodedra - #387
- [x] stock_orderpoint_uom - By @bodedra - #386 
- [ ] stock_partner_lot - By @agungrachmatulah - #419 
- [x] stock_putaway_product - By @asaunier - #380 
- [x] stock_quant_manual_assign - ~~By @fanha99 - #361~~ - By @cubells - #508 
- [x] ~~stock_quant_merge~~ Not needed anymore as now there's no quant fragmentation
- [ ] stock_quant_reserved_qty_uom
- [x] stock_removal_location_by_priority - By @lreficent - #483 
- [ ] stock_reord_rule
- [ ] stock_reserve - By @RodrigoBM - #883 
- [ ] stock_reserve_sale - By @RodrigoBM - #886 
- [x] stock_valuation_account_manual_adjustment - By @lreficent - #371 
- [x] stock_warehouse_orderpoint_stock_info - By @mpanarin - #376 
- [x] stock_warehouse_orderpoint_stock_info_unreserved - By @mpanarin - #377

**Comment by blutecsolutions** [comment]
All the best, thanks for all the efforts put in the OCA modules.

**Comment by fanha99** [comment]
Hi all,
I think the stock_quant_merge module should be remove.
in 11.0, the quant is different from 10.0. It store only amount in hand, and reserved amount of each lot. When a stock move done, the amount of stock move will be add or sub to the amount in hand if it is the same lot.

**Comment by conroyke56** [comment]
Hi All,
Desperate for some of these modules to be upgraded to 11.
Id be willing to pay using Freelancer or similar for anyone willing to do the work.

Cheers.

**Comment by pedrobaeza** [comment]
Please say which ones and then people can email you if interested.

**Comment by asaunier** [comment]
@yvaucher Please tag me for modules stock_putaway_product and stock_orderpoint_uom

**Comment by RCIclark** [comment]
Hello,
I'd be willing to pay towards someone updating the stock_mts_mto_rule to version 11.  Any help is greatly appreciated!

**Comment by ghost** [comment]
Hello,
I'm interested in having the stock_available_mrp module upgraded to work with version 11. I'd be happy to pay for it to be done ASAP! Thanks

**Comment by pedrobaeza** [comment]
There's already a migration in #428

**Comment by ghost** [comment]
we plan on migration partner_location_auto_create
@pedrobaeza I want to add an installation hook that create locations for existing partners. Is this a feature that OCA also would like?

**Comment by pedrobaeza** [comment]
@BT-kaberer I would say yes, but it should be the PSC / users of that addon who have to judge. You can propose the migration or even the hook and see what reviewers says. Other option for not speeding down the installation time is to put a button on config for doing that job, so it's optional to click on it and the installations doesn't delay.

**Comment by mustafatoraman** [comment]
Hi, thank you all for great work here!
Just wondering if there is any plan to migrate **sale_packaging** and **packaging_uom** modules to 11.0?
Thanks in advance!

**Comment by pedrobaeza** [comment]
Nobody has expressed its interest on migrating them for now.

**Comment by mustafatoraman** [comment]
Hi @pedrobaeza, thank you for letting me, sir. Looks like I'm the only one so far :) I'm looking for something like this for a long time and can't go back to V10.0 now. Thanks anyway!

**Comment by fanha99** [comment]
@mustafatoraman : could you please tell me the use case of those 2 modules? there are not much info about how to use them.

**Comment by mustafatoraman** [comment]
> @mustafatoraman : could you please tell me the use case of those 2 modules? there is not much info on how to use them.

@fanha99, simply they glue UoM and Packaging and allows you to sell products by their package configuration and show packaging as UoM in invoice lines. We sell pool mosaic tiles and each item boxed in different quantities. Instead of calculating manually, we will need something like this to speed up quote process. 

Here are a few images ;
![Imgur Image](https://image.ibb.co/mWBTST/Screen_Shot_2018_07_15_at_10_02_02_AM.png)
![Imgur Image](https://image.ibb.co/bKehnT/Screen_Shot_2018_07_15_at_10_08_06_AM.png)
![Imgur Image](https://image.ibb.co/g6r6E8/Screen_Shot_2018_07_15_at_10_09_17_AM.png)
![Imgur Image](https://image.ibb.co/kWCP1o/Screen_Shot_2018_07_15_at_10_10_57_AM.png)

**Comment by ProcessControl-JHF** [comment]
**packaging_uom** #469

**Comment by rousseldenis** [comment]
Migrating sale_packaging

**Comment by pedrobaeza** [comment]
Is it `product_secondary_unit` finally kept?

**Comment by rousseldenis** [comment]
We are investigating coexistence of both

**Comment by pedrobaeza** [comment]
Great, I think that at the end both cases are valid and can coexist

**Comment by emagdalenaC2i** [comment]
@pedrobaeza account_move_line_product - By @VRodrigo - #354 is already merged By @mreficent - #471 

Please, check account_move_line_stock_info - By @mreficent - #472 

Please, check packaging_uom - By @jhumfer - #469

Please, check stock_cycle_count - By @lreficent - #484

Please, add to the list stock_demand_estimate - By @mpanarin - #381 that is already migrated and merged

Please check stock_inventory_exclude_sublocation - By @lreficent - #478

Please check stock_inventory_lockdown - By @lreficent - #479

stock_orderpoint_automatic_creation - By @andreasdsp - #429 is closed and Supersedes by #502

Please check stock_orderpoint_manual_procurement - By @bodedra - #385

Please, add to the list stock_orderpoint_manual_procurement_uom - By @bodedra - #387 that is already migrated and merged

Please check stock_removal_location_by_priority - By @lreficent - #483

Please, add to the list stock_warehouse_orderpoint_stock_info_unreserved - By @mpanarin  - #377 that is already migrated and merged

**Comment by rousseldenis** [comment]
Do we welcome a new bot ? @emagdalenaC2i  @pedrobaeza :smile:

**Comment by pedrobaeza** [comment]
hehe @emagdalenaC2i has been very effective, but yes, this is always interesting, but the problem is to link each one to the proper module and so on. It requires the same to set something on each PR, and the problem is that people don't maintain up to date the list. @rousseldenis you are one of the main exceptions since you are PSC of these repos.

**Comment by emagdalenaC2i** [comment]
@rousseldenis Actually last time I almost passed the Turing test ;-)

**Comment by pedrobaeza** [comment]
I'm thinking that what we can maybe do is to have a bot that read comments. I have put the RFC in https://github.com/OCA/oca-github-bot/issues/32

**Comment by rousseldenis** [comment]
> hehe @emagdalenaC2i has been very effective, but yes, this is always interesting, but the problem is to link each one to the proper module and so on. It requires the same to set something on each PR, and the problem is that people don't maintain up to date the list. @rousseldenis you are one of the main exceptions since you are PSC of these repos

I will look at all logistics repos soon!

**Comment by kwoychesko** [comment]
Hello and thank you for all your organization and coding skills! Please forgive the noob question, but purchase_packaging does not appear in the list above -- does that mean it's ineligible to migrate to v11 for some reason (e.g. obsolete), or just that nobody else has expressed interest? Thanks again!

**Comment by rousseldenis** [comment]
@airmdb this list was based on modules that exist in previous branch. The v10 module wasn't merged at that time. It seems that there is no PR for that module at this moment. Please feel free to do it.

**Comment by emagdalenaC2i** [comment]
Please, check stock_change_qty_reason - By @andreasdsp - #417 that is already merged

**Comment by Odoolatam** [comment]
Hi, 
Any plans to migrate stock_inventory_revaluation to v11?
Thanks!

**Comment by RodrigoBM** [comment]
Hi,
Please, check Stock Reservation https://github.com/OCA/stock-logistics-warehouse/pull/883 that is already merged.
Thanks!

**Comment by RodrigoBM** [comment]
Hi,
Please, check Stock Reservation Sale  #886 that is already merged, This PR depend to approval this other #883
Thanks!

**Comment by thomaspaulb** [comment]
@fanha99 @pedrobaeza I am dealing with an 11.0 instance that has duplicate quants still:

![image](https://user-images.githubusercontent.com/1466356/107272411-f166bc00-6a4d-11eb-882e-56e229e372d6.png)

I don't know how they got there, but they are not getting merged because they have a different [in_date](https://github.com/OCA/OCB/blob/11.0/addons/stock/models/stock_quant.py#L328), and they are causing duplicate lines in a report.

Should I still port the `stock_quant_merge` module?

**Comment by pedrobaeza** [comment]
Odoo itself duplicates quants in some concurrent update cases. That's not critical anyway.
