### ISSUE TITLE
Missing readme.rst

### ISSUE THREAD

**Issue by yvaucher** [OCA/stock-logistics-warehouse#52]
- [x] ./stock_reserve @Doscaal #53
- [x] ./stock_location_ownership @Doscaal #54
- [x] ./stock_reserve_sale @Doscaal #55

**Comment by pedrobaeza** [comment]
All merged, so I close.
