### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-warehouse#90]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] stock_available - Being made by @stephankeller - #117
- [x] stock_available_immediately - Being made by @stephankeller - #117
- [ ] stock_available_sale
- [x] stock_available_mrp - Assigned to @cyrilgdn - #148
- [ ] stock_inventory_existing_lines
- [ ] stock_inventory_extended
- [ ] stock_inventory_line_price - @dlasley #275 
- [ ] stock_inventory_lockdown - @mreficent #282
- [ ] stock_location_ownership
- [ ] stock_move_location
- [ ] base_product_merge
- [ ] stock_orderpoint_creator
- [ ] configurable_stock_level
- [x] stock_mts_mto_rule - ~~By @jbeficent - #157~~ By @sylvain-garancher - #204 
- [x] stock_inventory_preparation_filter - By @chienandalu - #510 
- [ ] stock_lot_valuation
- [ ] stock_inventory_with_location
- [ ] stock_reord_rule
- [x] stock_reserve - By @katyukha - #189
- [ ] stock_reserve_sale - By @katyukha - #190
- [ ] stock_location_area_management
- [x] stock_location_area_data - By @dvdhinesh - #123 
- [ ] stock_optional_valuation
- [x] stock_quant_manual_assign - ~~By lbelorgey - #173~~ - By @jbeficent - #196 
- [x] stock_quant_merge - By lbelorgey - #174 
- [ ] partner_location_auto_create
- [x] stock_orderpoint_generator - By @cyrilgdn - #170

**Comment by clonedagain** [comment]
stock_available_mrp and stock_available_sale are migrating to v8, please refrain from porting to v9 until these PRs get merged:
- https://github.com/OCA/stock-logistics-warehouse/pull/93
- https://github.com/OCA/stock-logistics-warehouse/pull/81

**Comment by clonedagain** [comment]
@pedrobaeza can you please add stock_available, stock_available_sale and stock_available_mrp to the TODO list?

**Comment by stephankeller** [comment]
we are porting stock_available and stock_available_immediately to v9.

**Comment by pedrobaeza** [comment]
Noted!

**Comment by clonedagain** [comment]
@stephankeller if you didn't test stock_available_sale and stock_available_mrp yet, check if they can be useful to you. Maybe you'd consider migrating them too? Numérigraphe won't move to v9 so we can't help there.

**Comment by stephankeller** [comment]
@clonedagain sorry for the delay, we are aware of those modules but our customers don't need them so far.  So we have no plan to port them.  I will let you know if it changes.

**Comment by dvdhinesh** [comment]
stock_location_area_data #123

**Comment by cyrilgdn** [comment]
Starting to work on stock_available_mrp.

**Comment by cyrilgdn** [comment]
PR for  stock_orderpoint_generator (was  stock_orderpoint_creator)
https://github.com/OCA/stock-logistics-warehouse/pull/170

**Comment by katyukha** [comment]
PR for _stock_reserve_ and _stock_reserve_sale_ - #186

Also improvements for these addons: #187 #188
